### ISSUE TITLE
Mod request: Mekanism:generators

### ISSUE THREAD

**Issue by CptShad** [PSILONCRAFTED/ISSUES#2]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I'd like a module for the mod mekanism named Mekanism:Generators. http://aidancbrady.com/mekanism/download/

## Additional Information

**Comment by PSILONCRAFT** [comment]
use this repository instead https://github.com/PSILONCRAFT/psiloncrafted

this one is inactive
